services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timetracker_frontend
    restart: unless-stopped
    ports:
      - "3100:3000"
    environment:
      - NODE_ENV=production
